# /etc/nixos/system.nix — the configuration for a nix-on-illumos zone.
#
# This is the editable equivalent of /etc/nixos/configuration.nix on a
# NixOS host: the package set installed system-wide. To add or remove
# software, edit the `paths` list below.
#
# After editing, rebuild and switch the system profile in one atomic
# step:
#
#   nix-build /etc/nixos/system.nix -o /nix/var/nix/profiles/default
#
# (`nix-build -o` replaces the profile symlink atomically; bash, nix,
# and anything else under the merged bin/ pick up the new versions
# immediately.)
#
# `<nixpkgs>` must resolve to a checkout. Set NIX_PATH to point at one,
# e.g.:
#
#   nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
#   nix-channel --update
#
# or just clone a working copy and `export NIX_PATH=nixpkgs=/path/to/nixpkgs`.
#
# This file is also imported by ../make-zone-image.nix to build the
# initial system profile baked into the zone image, so the `paths` list
# below is the single source of truth for what lands under
# /nix/var/nix/profiles/default on first boot. Edits flow into both the
# image build and the in-zone rebuild by construction; the first
# `nix-build /etc/nixos/system.nix` from inside the zone is a no-op iff
# NIX_PATH points at the same nixpkgs revision the image was built
# from.
{ pkgs ? import <nixpkgs> { } }:

let
  # Declarative SMF service list (manifests generated by smf-lib.nix).
  # Folding the bundle into the profile exposes the XML at
  # /nix/var/nix/profiles/default/lib/svc/manifest/site/ — the input
  # for a future import-on-rebuild activation step. Imported via
  # pkgs.path rather than ./services.nix so this file works both from
  # the nixpkgs tree (image build) and as the standalone copy at
  # /etc/nixos/system.nix (in-zone rebuild, where <nixpkgs> resolves
  # to the shipped snapshot).
  services = import (pkgs.path + "/pkgs/stdenv/illumos-recipe/zone-root/services.nix") {
    inherit pkgs;
  };
in
pkgs.buildEnv {
  name = "nix-zone-system";

  paths = with pkgs; [
    # .out (not the package itself) because buildEnv would otherwise
    # try to include outputs like `man` that aren't always built.
    # nixVersions.nix_2_33 rather than pkgs.nix because the package-set
    # default is 2.31.5, which doesn't compile on illumos.
    nixVersions.nix_2_33.out
    bashInteractive
    coreutils
    rsync
    gitMinimal
    # Mozilla CA bundle. Lands at $out/etc/ssl/certs/ca-bundle.crt;
    # zone-root/builder.sh symlinks /etc/ssl/certs/{ca-bundle,
    # ca-certificates}.crt to it and /etc/profile exports
    # SSL_CERT_FILE / NIX_SSL_CERT_FILE pointing there. Removing this
    # entry breaks TLS for git / curl / nix at the next rebuild.
    cacert
  ] ++ [ services.bundle ];

  pathsToLink = [ "/bin" "/etc" "/lib" "/libexec" "/share" ];
  ignoreCollisions = true;
}
